version: '3.9'

services:
  nginx:
    image: nginx
    ports: 
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php-fpm
      - vueapp
  
  vueapp:
    container_name: vueapp
    build: ./front/
    volumes:
      - ./front/:/app
      - /app/node_modules
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true

  php-fpm:
    container_name: back
    build: ./php/
    volumes:
      - ./php:/var/www/html
      - ./var/www/html/vendor

  mysql:
    container_name: mysql
    build: ./docker/mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "todos"
      MYSQL_USER: "todos"
      MYSQL_PASSWORD: "todos"
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - "mysql:mysql"
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin:/var/www/html/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql